### ISSUE TITLE
Programs crashes in Play mode and passing

### ISSUE THREAD

**Issue by hvdkrogt** [new3Rs/a_master_of_go#62] opened 2019-01-10 22:42 UTC
Hello,

I cannot end a game in playmode because the program crashes after do a pass. It happens at the end of the games, but also in de middle of a game as a test.
This is on a new IPad Pro with 64 Gb.
It would be nice to be able to save a game while playing, this could perhaps also help reconstructing when it happens.

All the best, Harry

I just tested it on my Iphone 7+. It happens there also.
On my old Ipad mini there is no problem.

**Comment by y-ich** [comment] 2019-01-11 00:41
Thank you for purchasing my app and reporting the issue!

I could not reproduce the issue on my new iPad Pro with 64GB.
But I know that there are cases that the app crashes.
I keep investigating this issue.
Your idea for debugging is nice, I will try to implement it.

I am sorry for inconvenience and thank you for your comments.

**Comment by hvdkrogt** [comment] 2019-01-12 23:57
Hi Ishikawa,

The crash happens all the time when,  in play mode, I tick "pass". Even when no moves have been played. 
I have located some crash files of the ipad Pro, I think they are of AMOG. The crashfile names always start with ChildOfZero####.
I attach them, when looking at the you can see that the crash is in the AZ Engine (from what I find on the internet this might be the Az Neural Engine. I have no clue on what it means BTW, I am not a programmer.
But perhaps this helps you.

All the best, Harry



[ChildOfZero-2019-01-12-130106.txt](https://github.com/new3Rs/a_master_of_go/files/2752658/ChildOfZero-2019-01-12-130106.txt)
[ChildOfZero-2019-01-13-002557.txt](https://github.com/new3Rs/a_master_of_go/files/2752659/ChildOfZero-2019-01-13-002557.txt)
[ChildOfZero-2019-01-13-003444.txt](https://github.com/new3Rs/a_master_of_go/files/2752660/ChildOfZero-2019-01-13-003444.txt)
[ChildOfZero-2019-01-13-003557.txt](https://github.com/new3Rs/a_master_of_go/files/2752661/ChildOfZero-2019-01-13-003557.txt)

**Comment by y-ich** [comment] 2019-01-13 00:42
Thank you for your detail report, @hvdkrogt san!

Now I found that reproduction condition.
Battery saving is off and number of threads is greater than 1 and playing pass causes crash.
I will fix it in next version.

I am sorry for inconvenience and thank you for your cooperations!

**Comment by y-ich** [comment] 2019-01-13 02:33
The bug will be fixed in 1.4.0.

**Closed by y-ich** 2019-01-13 02:33 UTC
