### ISSUE TITLE
SGF from SmartGo Pro flagged as “invalid”

### ISSUE THREAD

**Issue by fireproof** [new3Rs/a_master_of_go#17] opened 2018-11-18 21:13 UTC
Kifu has handicap, comments, variations — can’t tell offhand which element is the issue, but the same file with variations removed is rejected too.

Saved from SmartGo Pro to Dropbox, then exported to Master of Go.
```
(;GM[1]FF[4]SZ[19]AP[SmartGo Kifu:4.7]
GN[2018-11-10c]
PW[Matthew]
PB[Don]BR[12kyu]
EV[Casual Game]
DT[2018-11-10]
PC[Coffee Bean & Tea Leaf, De La Vina St]
HA[5]
KM[0.5]
RE[W+40.5]
RU[Japanese Rules]
AB[dd][pd][jj][dp][pp]
PL[W]CH[1];W[qf];B[nc];W[rd]
(;B[jd];W[qc];B[pc];W[nq];B[qm];W[qq]
(;B[qp];W[pq]
(;B[qi];W[op];B[pm];W[fq];B[oo];W[dn];B[cn];W[cq]
(;B[cp];W[dq];B[ep];W[eq];B[dm];W[cf];B[ch];W[cc];B[dc];W[cd];B[dk];W[de]
;B[fd];W[db];B[cg];W[fc];B[ee];W[ed];B[ec];W[eb];B[df];W[ed];B[fe];W[no]
;B[on];W[fp];B[en];W[jc];B[hc];W[id];B[hd];W[kd];B[je];W[ic];B[ne];W[ie]
;B[ke];W[ld];B[qb];W[rb];B[qd];W[rc];B[lb];W[kb];B[lc];W[kc];B[md];W[ih]
;B[le];W[hb];B[gc];W[gb];B[he];W[if];B[kg];W[ef];B[ff];W[dg];B[eg];W[dh]
;B[eh];W[df];B[hg];W[ei];B[ig];W[ci];B[jf];W[fn];B[hf];W[fi];B[gg];W[gm]
;B[mo];W[nn];B[mp];W[np];B[jm];W[jo];B[kn];W[jn];B[lm];W[kq];B[mq];W[nl]
;B[lk];W[nj];B[pk];W[fh];B[cj];W[bi];B[hh];W[ii];B[gk];W[ik];B[jk];W[ij]
;B[il];W[jh];B[kh];W[jg];B[ge];W[ki];B[mh];W[li];B[ji];W[gj];B[in];W[io]
;B[hl];W[fk];B[mi];W[hn];B[mr];W[nr];B[js];W[ko];B[ln];W[mn];B[lo];W[ml]
;B[ll];W[rp];B[qo];W[jr];B[ks];W[is];B[lr];W[ir];B[ro];W[bk];B[bl];W[bj]
;B[ck];W[rh];B[ka];W[ib];B[ri];W[qh];B[ph];W[pg];B[og];W[of];B[oh];W[nf]
;B[mf];W[bp];B[bo];W[bq];B[al];W[ng];B[pe];W[pf];B[nh];W[oe];B[od];W[pb]
;B[ob];W[qa];B[oa];W[mj];B[lj];W[pi];B[oi];W[mg];B[lg];W[oj];B[pj];W[si]
;B[sj];W[sh];B[rj];W[rq];B[gl];W[em];B[do];W[el];B[ek];W[fg];B[fl];W[gi]
;B[fm];W[fo];B[fj];W[ja];B[pa];W[qb];B[la];W[ol];B[pl];W[so];B[sn];W[sp]
;B[rm];W[kr];B[ls];W[ns];B[ej];W[qe];B[hm];W[gn];B[om];W[ao];B[an];W[ap]
;B[ak];W[aj];B[im];W[di];B[re];W[rf];B[kp];W[jp];B[lp];W[hk];B[hi];W[hj]
;B[mk];W[dj];B[ms];W[eo];B[dl];W[];B[hp];W[ho];B[mm];W[nm];B[nk];W[ok];B[ni]
;W[];B[];
TB[ka:pa][lb:oc][gc:hg][pc:pe][fd:ff][jd:jf][md:mf][nd:ne][od][qd][ee][ke:ln][ig][og:oi][hh:hi][mh:ni][ph:pp][ji:jm][qi:qp][ri:ro][cj:cp][ej:en][fj:fm][sj:sn][ak:an][dk:dp][gk:gl][mk:nk][bl:bo][hl:im][mm][om:oo][in][lo:mp][ep][kp][mq:ms][lr:ls][js:ks]
TW[aa:bj][ca:di][ea:jb][qa:sc][kb:kd][pb][ec:ed][fc][ic:if][jc][ld][rd:sh][oe:of][qe:qh][ef:ei][nf:ng][pf:pg][fg:fi][jg:jh][mg][ih:ik][gi:gj][si][dj][hj:hk][mj:oj][bk][ok:ol][ml:nl][gm:gs][nm:ns][fn:fs][hn:hs][jn:jr][mn][ao:as][eo][io:is][ko][so:ss][bp:bs][op:os][rp:rs][cq:es][kq:kr][pq:qs]
DS[re][cg:ch][ki:li][hp];W[bn];B[];W[])
(;B[dq];W[cp];B[do];W[co];B[cm];W[dr]
(;B[en])
(;B[er];W[cr];B[eq])))
(;B[op]
(;W[oq])
(;W[np];B[oq];W[or]
(;B[pr];W[qr];B[nr];W[ps];B[mr])
(;B[no]))
(;W[nr];B[mo])))
(;B[pq];W[qp];B[qo];W[pr];B[or];W[qr];B[oq];W[ro]
(;B[qn])
(;B[rn];W[po];B[qn];W[oo];B[rp];W[rq];B[so];W[sr])))
(;B[
```

**Comment by y-ich** [comment] 2018-11-19 02:03
@fireproof san,

Thank you for reporting the problem!
And I am sorry for inconvenience.
I will check it.

For you information about file operation tips.
(I guess if you already tried both the above operation and the below)
SmartGo Pro has a copy button in the share menu.
Copy SGF into pasteboard, invoke "A Master of Go", then "Paste SGF for Study", will make it easy just a little.

Thank you for using my app!

**Comment by y-ich** [comment] 2018-11-19 12:56
@fireproof san,

Your SGF has two invalid points.
1. SGF is not finished yet. see the last line.
2. There is a new line between ";" and "TB" in the middle part.
(SGF specification does not allow it in my understanding.)

No. 1 is fatal.
About No. 2, if it is usual in SGF by SmartGo, I will consider to treat it.

I wonder if you edit SGF by mistake when pasting.
Could you paste this SGF again?
Thank you for your collaboration!

**Comment by fireproof** [comment] 2018-11-19 16:17
Sorry about leaving that last move off -- here is the full contents, copied directly from the original SGF using BBEdit.
```
(;GM[1]FF[4]SZ[19]AP[SmartGo Kifu:4.7]
GN[2018-11-10c]
PW[Matthew]
PB[Don]BR[12kyu]
EV[Casual Game]
DT[2018-11-10]
PC[Coffee Bean & Tea Leaf, De La Vina St]
HA[5]
KM[0.5]
RE[W+40.5]
RU[Japanese Rules]
AB[dd][pd][jj][dp][pp]
PL[W]CH[1];W[qf];B[nc];W[rd]
(;B[jd];W[qc];B[pc];W[nq];B[qm];W[qq]
(;B[qp];W[pq]
(;B[qi];W[op];B[pm];W[fq];B[oo];W[dn];B[cn];W[cq]
(;B[cp];W[dq];B[ep];W[eq];B[dm];W[cf];B[ch];W[cc];B[dc];W[cd];B[dk];W[de]
;B[fd];W[db];B[cg];W[fc];B[ee];W[ed];B[ec];W[eb];B[df];W[ed];B[fe];W[no]
;B[on];W[fp];B[en];W[jc];B[hc];W[id];B[hd];W[kd];B[je];W[ic];B[ne];W[ie]
;B[ke];W[ld];B[qb];W[rb];B[qd];W[rc];B[lb];W[kb];B[lc];W[kc];B[md];W[ih]
;B[le];W[hb];B[gc];W[gb];B[he];W[if];B[kg];W[ef];B[ff];W[dg];B[eg];W[dh]
;B[eh];W[df];B[hg];W[ei];B[ig];W[ci];B[jf];W[fn];B[hf];W[fi];B[gg];W[gm]
;B[mo];W[nn];B[mp];W[np];B[jm];W[jo];B[kn];W[jn];B[lm];W[kq];B[mq];W[nl]
;B[lk];W[nj];B[pk];W[fh];B[cj];W[bi];B[hh];W[ii];B[gk];W[ik];B[jk];W[ij]
;B[il];W[jh];B[kh];W[jg];B[ge];W[ki];B[mh];W[li];B[ji];W[gj];B[in];W[io]
;B[hl];W[fk];B[mi];W[hn];B[mr];W[nr];B[js];W[ko];B[ln];W[mn];B[lo];W[ml]
;B[ll];W[rp];B[qo];W[jr];B[ks];W[is];B[lr];W[ir];B[ro];W[bk];B[bl];W[bj]
;B[ck];W[rh];B[ka];W[ib];B[ri];W[qh];B[ph];W[pg];B[og];W[of];B[oh];W[nf]
;B[mf];W[bp];B[bo];W[bq];B[al];W[ng];B[pe];W[pf];B[nh];W[oe];B[od];W[pb]
;B[ob];W[qa];B[oa];W[mj];B[lj];W[pi];B[oi];W[mg];B[lg];W[oj];B[pj];W[si]
;B[sj];W[sh];B[rj];W[rq];B[gl];W[em];B[do];W[el];B[ek];W[fg];B[fl];W[gi]
;B[fm];W[fo];B[fj];W[ja];B[pa];W[qb];B[la];W[ol];B[pl];W[so];B[sn];W[sp]
;B[rm];W[kr];B[ls];W[ns];B[ej];W[qe];B[hm];W[gn];B[om];W[ao];B[an];W[ap]
;B[ak];W[aj];B[im];W[di];B[re];W[rf];B[kp];W[jp];B[lp];W[hk];B[hi];W[hj]
;B[mk];W[dj];B[ms];W[eo];B[dl];W[];B[hp];W[ho];B[mm];W[nm];B[nk];W[ok];B[ni]
;W[];B[];
TB[ka:pa][lb:oc][gc:hg][pc:pe][fd:ff][jd:jf][md:mf][nd:ne][od][qd][ee][ke:ln][ig][og:oi][hh:hi][mh:ni][ph:pp][ji:jm][qi:qp][ri:ro][cj:cp][ej:en][fj:fm][sj:sn][ak:an][dk:dp][gk:gl][mk:nk][bl:bo][hl:im][mm][om:oo][in][lo:mp][ep][kp][mq:ms][lr:ls][js:ks]
TW[aa:bj][ca:di][ea:jb][qa:sc][kb:kd][pb][ec:ed][fc][ic:if][jc][ld][rd:sh][oe:of][qe:qh][ef:ei][nf:ng][pf:pg][fg:fi][jg:jh][mg][ih:ik][gi:gj][si][dj][hj:hk][mj:oj][bk][ok:ol][ml:nl][gm:gs][nm:ns][fn:fs][hn:hs][jn:jr][mn][ao:as][eo][io:is][ko][so:ss][bp:bs][op:os][rp:rs][cq:es][kq:kr][pq:qs]
DS[re][cg:ch][ki:li][hp];W[bn];B[];W[])
(;B[dq];W[cp];B[do];W[co];B[cm];W[dr]
(;B[en])
(;B[er];W[cr];B[eq])))
(;B[op]
(;W[oq])
(;W[np];B[oq];W[or]
(;B[pr];W[qr];B[nr];W[ps];B[mr])
(;B[no]))
(;W[nr];B[mo])))
(;B[pq];W[qp];B[qo];W[pr];B[or];W[qr];B[oq];W[ro]
(;B[qn])
(;B[rn];W[po];B[qn];W[oo];B[rp];W[rq];B[so];W[sr])))
(;B[qc]))

```

**Comment by fireproof** [comment] 2018-11-19 16:22
> SmartGo Pro has a copy button in the share menu.
> Copy SGF into pasteboard, invoke "A Master of Go", then "Paste SGF for Study", will make it easy just a little.

Yes, copy-and-paste is very convenient! I'm using the Dropbox -> Master of Go method because I frequently edit  or review games outside of the iPad I use to record games. Thanks for making this method available, too.

**Comment by y-ich** [comment] 2018-11-19 23:54
@fireproof san,

Thank you for pasting SGF.
Now I made sure that the problem is only No. 1 and  currently if you remove the new line between ";" and "TB[ka:pa], it will work.
Sorry for inconvenience.

I will take care of this problem in the next version.

Thank you for using my app!
I hope your happy Go life.

**Comment by y-ich** [comment] 2018-11-20 01:06
fixed in next version

**Closed by y-ich** 2018-11-20 01:06 UTC
Labels: invalid
